services:
  api-gateway:
    build:
      context: .
      dockerfile: Dockerfile
      args:
        - NEXUS_USERNAME=${{ shared.NEXUS_USERNAME }}
        - NEXUS_PASSWORD=${{ shared.NEXUS_PASSWORD }}
    ports:
      - "8080:8080"
    environment:
      - ALLOWED_ORIGINS=${{ shared.ALLOWED_ORIGINS }}
      - DATABASE_NAME=${{ shared.DATABASE_NAME }}
      - ELASTICSEARCH_PASSWORD=${{ shared.ELASTICSEARCH_PASSWORD }}
      - ELASTICSEARCH_URL=${{ shared.ELASTICSEARCH_URL }}
      - ELASTICSEARCH_USERNAME=${{ shared.ELASTICSEARCH_USERNAME }}
      - JWT_SECRET=${{ shared.JWT_SECRET }}
      - KAFKA_BOOTSTRAP_SERVERS=${{ shared.KAFKA_BOOTSTRAP_SERVERS }}
      - MONGO_URI=${{ shared.MONGO_URI }}
      - NEXUS_URL=${{ shared.NEXUS_URL }}
      - NEXUS_USERNAME=${{ shared.NEXUS_USERNAME }}
      - NEXUS_PASSWORD=${{ shared.NEXUS_PASSWORD }}
      - GOOGLE_API_KEY=${{ shared.GOOGLE_API_KEY }}
      - GOOGLE_CLIENT_ID=${{ shared.GOOGLE_CLIENT_ID }}
      - GOOGLE_CLIENT_SECRET=${{ shared.GOOGLE_CLIENT_SECRET }}
      - GOOGLE_REDIRECT_URI=${{ shared.GOOGLE_REDIRECT_URI }}
    restart: always